### ISSUE TITLE
Enable sql_require_primary_key per default in Group Replication setup

### ISSUE THREAD

**Issue by bezio** [percona/percona-server-mysql-operator#912]
### Proposal

Due to the nature of group replication to insist on having primary keys on innodb-tables to ensure data consistency it would be good to have set sql_require_primary_key=on by default when such a cluster is bootstrapped.
https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_sql_require_primary_key

This can prevent issues like broken backups (better: restores) and help avoiding issues when upgrading software-versions.

### Is this a feature you are interested in implementing yourself?

No

**Comment by remidinishanth** [comment]
Hey, I'm not from Percona team but

Did you try setting

```
spec:
  secretsName: cluster1-secrets
  sslSecretName: cluster1-ssl
  
  mysql:
    clusterType: group-replication
    autoRecovery: true
    size: 3
    image: percona/percona-server:8.0.28
    
    # MySQL Configuration Section
    configuration: |
      sql_require_primary_key=ON
```

I saw that configuration option is present in

```
func (c *Configurable) GetConfiguration() string {
	cr := apiv1alpha1.PerconaServerMySQL(*c)
	return cr.Spec.MySQL.Configuration
}
```


Similar config change is being at percona-server-mysql-operator/e2e-tests/tests/config/02-config-through-cr.yaml
